Plugin:
  # Command names that will be registered as main plugin commands.
  # Do not leave this empty. Split multiple names with a comma.
  Command_Aliases: excellentenchants,eenchants
  # Localized plugin name. It's used in messages and with internal placeholders.
  Name: ExcellentEnchants
  # Plugin prefix. Used in messages.
  # You can use %plugin_name_localized% placeholder for a plugin name.
  Prefix: '#fdf35e%plugin_name%#d4d9d8 » '
  # Sets the plugin language.
  # It will use language config from the '/lang/' sub-folder for specified language code.
  # By default uses your system's default locale.
  Language: cn
Tasks:
  Arrow_Trail:
    # Sets how often (in ticks) arrow trail particle effects will be spawned behind the arrow.
    Tick_Interval: 1
  Passive_Enchants:
    # Sets how often (in ticks) the plugin will attempt to trigger passive enchantment effects on all alive entities.
    # For best results it's recommened to keep this value smaller, but at the same rate as enchantment 'Trigger_Interval' settings.
    # Examples:
    # --- Global: 100 ticks; Regrowth: 100 ticks; Saturation: 100 ticks;
    # --- Global: 50 ticks, Regrowth: 100 ticks; Saturation: 150 ticks;
    Trigger_Interval: 100
Enchantments:
  # [EXPERIMENTAL - DO NOT TOUCH]
  # Sets whether or not enchantment distribution will be handled by vanilla server mechanics.
  Internal_Distributor: false
  Charges:
    # Enables the enchantment Charges feature.
    # https://github.com/nulli0n/ExcellentEnchants-spigot/wiki/Charges-System
    Enabled: false
    # Enchantment charges format depends on amount of charges left (in percent).
    # If you don't want to display charges, leave only keys with negative values.
    # Use '%amount%' placeholder for amount of charges.
    Format:
      '0': '#ff9a9a(%amount%⚡)'
      '25': '#ffc39a(%amount%⚡)'
      '50': '#f6ff9a(%amount%⚡)'
      '75': '#bcff9a(%amount%⚡)'
    # When enabled, only item material will be checked to determine if item can be used as an enchantment fuel.
    # When disabled (default), it will compare the whole item meta including name, lore, model data etc.
    Compare_Material_Only: false
    # Default item used to recharge item's enchantments on anvils.
    # If you want different item for certain enchantments, you can do it in that enchantment configs.
    # Item Options: https://github.com/nulli0n/NexEngine-spigot/wiki/Configuration-Tips#scalable-sections
    Fuel_Item:
      Material: LAPIS_LAZULI
  # A list of enchantments, that will be disabled and removed from the game (server).
  # Enchantment names are the same as enchantment file name in /enchants/ folder. ! Must be in lower_case !
  # Example: To disable 'Explosive Arrows' you need to add 'explosive_arrows' here.
  Disabled:
  - enchant_name
  - other_enchant
  # Here you can disable certain enchantments in certain worlds.
  # Enchantment names are the same as enchantment file name in /enchants/ folder. ! Must be in lower_case !
  # To disable all enchantments for a world, use '*' instead of enchantment names.
  Disabled_In_Worlds:
    your_world_name:
    - enchantment_name
    - ice_aspect
  Display:
    # Sets how enchantment names and descriptions will be handled on items.
    # 1 = Plain modification of item's lore (lore changes are real and persistent).
    # 2 = Packet modification of item's lore (no real changes are made to the items). Requires ProtocolLib.
    # Plain mode is faster, but may not reflect all changes immediately.
    # Packet mode is slower, but instantly reflect all changes. In creative mode, there is a chance for lore duplication.
    Mode: 1
  Description:
    # When 'true', adds the enchantment description to item lore under enchantment names.
    # For Display-Mode = 2 description is not shown while you're in Creative gamemode.
    Enabled: true
    # Sets whether or not only enchanted books will have enchantment descriptions.
    Books_Only: false
    # Sets the global enchantment description format.
    Format: '&8▸ %description%'
  Item:
    # How many of custom enchantments the item can contain at the same time?
    Max_Custom_Enchants: 3
    # Set this to 'true' to allow Sword enchantments for Axes.
    Sword_Enchants_To_Axes: true
    # Set this to 'true' to allow Bow enchantments for Crossbows.
    Bow_Enchants_To_Crossbows: true
    # Set this to 'true' to allow Chestplate enchantments for Elytras.
    Chestplate_Enchants_To_Elytra: false
  Entity:
    # When enabled, passive enchantments (permanent potion effects, regeneration, etc.) will be applied to mobs as well.
    # Disable this if you're experiencing performance issues.
    Apply_Passive_Enchants_To_Mobs: true
  # Sets whether or not enchanted books in villager trades will have only 1 enchant, vanilla or custom one.
  Single_Enchant_In_Villager_Books: true
  # Settings for the different ways of obtaining enchantments.
  Obtaining:
    Mob_Spawning:
      Enabled: true
      Enchantments:
        Total_Maximum: 4
        Custom_Generation_Chance: 80.0
        Custom_Minimum: 0
        Custom_Maximum: 2
    Loot_Generation:
      Enabled: true
      Enchantments:
        Total_Maximum: 4
        Custom_Generation_Chance: 80.0
        Custom_Minimum: 0
        Custom_Maximum: 2
    Fishing:
      Enabled: true
      Enchantments:
        Total_Maximum: 4
        Custom_Generation_Chance: 80.0
        Custom_Minimum: 0
        Custom_Maximum: 2
    Enchanting_Table:
      Enabled: true
      Enchantments:
        Total_Maximum: 4
        Custom_Generation_Chance: 80.0
        Custom_Minimum: 0
        Custom_Maximum: 2
    Villagers:
      Enabled: true
      Enchantments:
        Total_Maximum: 4
        Custom_Generation_Chance: 80.0
        Custom_Minimum: 0
        Custom_Maximum: 2
